INSERT INTO categories (id, name, slug, description, color, sort_order, is_active) VALUES
  (1, 'World', 'world', 'Global affairs, diplomacy and stories shaping the world around us.', '#cc3f3f', 1, 1),
  (2, 'Technology', 'technology', 'The tools, platforms and breakthroughs changing how we live and work.', '#2563eb', 2, 1),
  (3, 'Business', 'business', 'Markets, companies and the people who keep the economy moving.', '#d97706', 3, 1),
  (4, 'Culture', 'culture', 'Books, film, music, art and the ideas that define the moment.', '#7c3aed', 4, 1),
  (5, 'Science', 'science', 'Discovery, health, climate and the natural world explained.', '#059669', 5, 1);

INSERT INTO site_settings (key, value) VALUES
  ('site_name', 'bengvarna'),
  ('site_description', 'Fast to read. Fast to publish. Beautiful everywhere.'),
  ('logo_url', ''),
  ('default_social_image', 'https://images.unsplash.com/photo-1504711434969-e33886168f5c?w=1200&h=630&fit=crop'),
  ('default_seo_title', 'bengvarna — Modern news, beautifully delivered'),
  ('default_seo_description', 'bengvarna is a fast, elegant digital news platform built for readers on every screen.');

INSERT INTO articles (id, title, slug, excerpt, content, cover_image_url, category_id, author, status, seo_title, seo_description, published_at) VALUES
(1, 'Global Accord on Ocean Conservation Signed by 120 Nations', 'global-accord-ocean-conservation-120-nations',
 'After two years of intense negotiations, delegates from 120 countries have signed a landmark agreement to protect a third of the world''s oceans by 2035. The deal marks the largest coordinated marine conservation effort in history.',
 '<p>After two years of intense negotiations, delegates from 120 countries signed a landmark agreement on Saturday to place a third of the world''s oceans under formal protection by 2035. The accord, finalized in the early hours of the morning, is being described by diplomats as the largest coordinated marine conservation effort in history.</p><p>The agreement creates a legal framework for establishing marine protected areas in international waters, which cover nearly two-thirds of the ocean. It also sets binding targets for restoring damaged coastal ecosystems and establishes a new global fund to help smaller nations monitor and enforce the new rules.</p><blockquote>This is a rare moment when the world chose the long term over the convenient. The ocean does not recognize borders, and now neither does our ambition to protect it.</blockquote><p>Negotiations nearly collapsed twice. A coalition of coastal states argued that ambitious protection targets would cripple fishing communities that depend on open waters for their livelihoods. A compromise brokered in the final week carves out transitional allowances for small-scale fisheries while phasing out industrial bottom-trawling in newly protected zones over eight years.</p><h2>What the agreement actually changes</h2><p>Under the new framework, a scientific committee will designate priority areas for protection, with particular attention to seamounts, deep-water coral reefs and migratory corridors. Nations that ratify the agreement commit to submitting national action plans within three years.</p><ul><li>At least 30 percent of international waters must be under enforceable protection by 2035.</li><li>Industrial bottom-trawling will be phased out of protected zones within eight years.</li><li>A 4-billion-dollar fund will support monitoring and enforcement in developing coastal states.</li></ul><figure><img src="https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&q=80" alt="Coastline at sunrise"><figcaption>Coastal ecosystems are expected to recover quickly once protections take effect.</figcaption></figure><p>Marine scientists welcomed the deal but cautioned that enforcement remains the hardest part. Satellite monitoring has improved dramatically, but patrolling millions of square kilometres of open ocean will require cooperation at a scale that has historically been difficult to sustain.</p><h2>The road to ratification</h2><p>The agreement now moves to national legislatures. It enters into force once at least 60 countries ratify it, a threshold organizers believe can be reached within two years. Several large economies have already signaled they will fast-track the process.</p><p>For the negotiators who spent sleepless weeks refining the final text, the mood in the conference hall was one of cautious relief. The ocean, they noted, has a long memory — and now, perhaps, a real defense.</p>',
 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1600&q=80', 1, 'Anika Rahman', 'published', '120 Nations Sign Historic Global Ocean Conservation Accord', 'Delegates from 120 countries signed a landmark agreement to protect a third of the world''s oceans by 2035 — the largest coordinated marine conservation effort ever.',
 '2026-08-17T09:00:00.000Z'),

(2, 'Open-Source AI Models Are Quietly Powering the Enterprise', 'open-source-ai-models-quietly-powering-enterprise',
 'A new survey of technology leaders shows open-weight models have moved from experiment to backbone, running in production across finance, healthcare and retail. The era of the locked-down model may be ending faster than anyone predicted.',
 '<p>Three years ago, open-source artificial intelligence was a curiosity — impressive demos that fell short of the polished models sold by the big labs. Today, according to a new survey of technology leaders, open-weight models are running in production at more than half of large enterprises, handling everything from document processing to customer support.</p><p>The shift has been driven by a simple calculation. Fine-tuning an open model on internal data now costs a fraction of what it costs to call a proprietary API at scale, and the results, in many specialized tasks, are competitive or better.</p><blockquote>The conversation changed from "can we trust it" to "can we afford not to." Open models let us own our data pipeline end to end.</blockquote><h2>Where enterprises are deploying open models</h2><p>The survey, which polled 800 technology decision-makers, found open-weight models most common in three areas: internal knowledge retrieval, customer-facing chatbots and code generation. Financial services led adoption, with healthcare close behind.</p><ul><li>Internal knowledge assistants: 61 percent of adopters</li><li>Customer support automation: 54 percent</li><li>Developer tools and code review: 48 percent</li><li>Document and contract analysis: 41 percent</li></ul><p>Security teams, once the loudest skeptics, have become some of the strongest advocates. Running models on their own infrastructure eliminates the need to send sensitive data to third-party servers — a compliance advantage that has tipped several large deals.</p><h2>The risks that remain</h2><p>Nobody in the industry claims the open route is without friction. Model evaluation is still immature, and the burden of patching, monitoring and updating falls entirely on the adopting company. Governance frameworks are only beginning to catch up.</p><figure><img src="https://images.unsplash.com/photo-1620712943543-bcc4688e7485?w=1200&q=80" alt="Robotic arm in a modern laboratory"><figcaption>Open models increasingly run on enterprise-owned infrastructure.</figcaption></figure><p>Still, the direction of travel seems clear. What began as an ideological argument about openness has become a pragmatic argument about cost, control and speed — and pragmatism usually wins.</p><p>Analysts now expect open models to account for more than half of enterprise AI workloads within three years. The era of the locked-down model, it seems, is ending faster than anyone predicted.</p>',
 'https://images.unsplash.com/photo-1620712943543-bcc4688e7485?w=1600&q=80', 2, 'Daniel Okafor', 'published', 'Open-Source AI Models Now Power Most Enterprise AI Workloads', 'Open-weight AI models have moved from experiment to production backbone, running across finance, healthcare and retail, a new survey shows.',
 '2026-08-16T14:30:00.000Z'),

(3, 'Why Long-Form Journalism Is Making a Comeback', 'long-form-journalism-making-a-comeback',
 'Against every prediction, readers are returning to deep, carefully reported stories. Publishers are responding with dedicated slow-journalism desks and subscriber-only long reads that routinely outperform breaking news.',
 '<p>For a decade, the received wisdom was that attention spans were collapsing and that journalism would survive only in snackable fragments. The data now tells a different story. Across major publishers, long-form journalism — deeply reported stories of 3,000 words or more — is driving record engagement and, crucially, record subscriptions.</p><p>Industry analytics show that while breaking news still generates the most clicks, long reads generate the most loyalty. A subscriber who reads one long-form piece in their first month is dramatically more likely to renew than one who reads a dozen short updates.</p><blockquote>Speed tells people what happened. Depth tells them why it matters. Readers have figured out the difference, and they are willing to pay for the second.</blockquote><h2>The economics of slow journalism</h2><p>Publishers have responded by creating dedicated slow-journalism desks, teams freed from the daily news cycle and given weeks — sometimes months — to pursue a single story. The model borrows from investigative units but broadens the remit: profiles, essays, oral histories and reconstructions.</p><ul><li>Long reads convert readers to subscribers at three times the rate of news updates.</li><li>Average time on page for long-form pieces has risen 40 percent since 2021.</li><li>Several outlets now publish long reads as standalone audio editions, doubling reach.</li></ul><p>Magazine editors who once feared the algorithm have found an unexpected ally: recommendation feeds reward completion time, and a story people read to the end is a story the feed shows to more people.</p><h2>A different kind of attention</h2><p>Media researchers caution against confusing the trend with a rejection of speed. Readers still want to know what is happening right now. What has changed is that they no longer accept the trade-off that speed once demanded — that depth must be sacrificed to urgency.</p><figure><img src="https://images.unsplash.com/photo-1504711434969-e33886168f5c?w=1200&q=80" alt="Stack of newspapers on a wooden table"><figcaption>Print and digital long reads are both enjoying a quiet renaissance.</figcaption></figure><p>The revival has been especially visible among younger readers, who grew up entirely online. Having been raised on infinite feeds, many describe long-form journalism as a relief — a space where attention is finally treated as something worth asking for.</p><p>Whether the economics hold through the next downturn is an open question. But for now, the slowest format in journalism is proving to be its most durable bet.</p>',
 'https://images.unsplash.com/photo-1504711434969-e33886168f5c?w=1600&q=80', 4, 'Sofia Marchetti', 'published', 'The Quiet Comeback of Long-Form Journalism', 'Deeply reported stories are driving record subscriptions and engagement as readers rediscover the value of slow journalism.',
 '2026-08-15T11:15:00.000Z'),

(4, 'Grid-Scale Batteries Reach Record Deployment This Year', 'grid-scale-batteries-record-deployment',
 'Energy storage installations have more than doubled year over year, with grid-scale batteries now displacing peaker plants in a dozen markets. Analysts say the storage era has officially begun.',
 '<p>Grid-scale battery storage installations more than doubled in the first half of the year compared with the same period last year, according to new industry figures — a pace that has surprised even the sector''s most optimistic analysts and marks the arrival of storage as a mainstream part of the electricity system.</p><p>The surge is concentrated in markets where daytime solar generation now routinely exceeds demand. Batteries that charge on cheap midday power and discharge during the evening peak have become the most profitable asset class in several electricity markets, displacing gas peaker plants that once commanded premium prices for their flexibility.</p><blockquote>We used to think of storage as a supporting actor. Now it is being booked as the headliner, and the economics are not close.</blockquote><h2>What changed</h2><p>Three forces converged. Battery cell prices fell below the threshold where storage became cheaper than new peaker capacity; market rules caught up, allowing batteries to be paid for the services they provide; and connection queues for new gas plants stretched to five years while battery projects could be built in eighteen months.</p><ul><li>Average duration of new installations has risen from two hours to four hours.</li><li>Utility-scale storage capacity is projected to triple again by 2028.</li><li>Recycling programs now recover over 90 percent of battery materials.</li></ul><figure><img src="https://images.unsplash.com/photo-1509391366360-2e959784a276?w=1200&q=80" alt="Solar panels under a blue sky"><figcaption>Cheap midday solar power has made storage the most profitable new asset in many grids.</figcaption></figure><h2>The next bottleneck</h2><p>The constraint has shifted from cost to interconnection. Grid operators, designed for an era of a few hundred large generators, now face applications for thousands of smaller, smarter assets. Reforming those processes, analysts argue, will determine how fast the storage boom can continue.</p><p>For consumers, the effect will be felt in the evening. The cheapest hour of electricity is increasingly the middle of the day — a complete inversion of the pricing structure that governed the grid for a century, and a sign of how thoroughly renewables have rewritten the rules.</p>',
 'https://images.unsplash.com/photo-1509391366360-2e959784a276?w=1600&q=80', 5, 'Mira Chen', 'published', 'Grid-Scale Battery Deployments Hit Record High', 'Battery storage installations doubled year over year as cheap solar power made storage the most profitable asset in a dozen electricity markets.',
 '2026-08-14T08:45:00.000Z'),

(5, 'European Chipmakers Plan 40 Billion Euro Expansion', 'european-chipmakers-40-billion-expansion',
 'Three of Europe''s largest semiconductor companies have announced a coordinated 40-billion-euro investment program, aiming to double the continent''s share of advanced chip production by the end of the decade.',
 '<p>Three of Europe''s largest semiconductor companies unveiled a coordinated 40-billion-euro investment program on Wednesday, a move that aims to double the continent''s share of advanced chip production by the end of the decade and reduce dependence on overseas foundries.</p><p>The announcement, made jointly at an industry summit, combines new fabrication facilities, research campuses and workforce training programs across four countries. Public subsidies will cover roughly a quarter of the total, with the remainder funded by the companies themselves.</p><h2>Why now</h2><p>Europe currently accounts for about 8 percent of global chip manufacturing capacity, down from more than 20 percent two decades ago. Supply-chain shocks during the pandemic exposed the fragility of that position, and subsequent subsidy programs in other regions accelerated a race to onshore production.</p><p>The new program focuses on the most strategically sensitive segments: advanced logic for automotive and industrial applications, power semiconductors and specialized chips for defense and aerospace.</p><ul><li>Two new fabrication plants, one of which will be operational by 2029.</li><li>15,000 technical jobs, plus a parallel apprenticeship pipeline.</li><li>Research partnerships with 40 universities across the continent.</li></ul><blockquote>This is not about winning the whole race. It is about making sure we are never again a passenger in someone else''s supply chain.</blockquote><h2>Skepticism and the long view</h2><p>Analysts noted that the industry has announced ambitious European expansions before, only to scale back when cycles turned. The difference this time, they say, is the structure of the funding — long-term contracts with automotive and industrial customers that guarantee demand for the new capacity.</p><figure><img src="https://images.unsplash.com/photo-1518770660439-4636190af475?w=1200&q=80" alt="Close-up of a microchip on a circuit board"><figcaption>Advanced logic chips for automotive and industrial use are the program''s focus.</figcaption></figure><p>The first construction is scheduled to begin next spring. If the schedule holds, the program''s architects believe Europe could reach 15 percent of global advanced production by 2031 — modest by global standards, but enough to change the strategic arithmetic.</p>',
 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=1600&q=80', 2, 'Lena Vogel', 'published', 'European Chipmakers Announce 40 Billion Euro Expansion Plan', 'A coordinated 40-billion-euro investment aims to double Europe''s share of advanced semiconductor production by the end of the decade.',
 '2026-08-13T16:20:00.000Z'),

(6, 'Small Shops Turn to Community Lending as Banks Retreat', 'small-shops-community-lending-banks-retreat',
 'Neighborhood businesses squeezed out of traditional credit markets are finding capital through community loan funds, and the repayment rates are confounding expectations.',
 '<p>The bakery on the corner needed 30,000 dollars for a new oven. The bank that had held its account for two decades said no. Six weeks later, the money arrived anyway — from a community loan fund backed by 400 local residents, each lending as little as 50 dollars.</p><p>Stories like this have become common. As traditional banks have tightened lending to small businesses, community lending funds have exploded, channeling capital from ordinary savers directly to the shops, workshops and restaurants in their neighborhoods.</p><blockquote>People understand their street better than any credit model. A lender who drinks your coffee every morning knows you are good for it.</blockquote><h2>How the model works</h2><p>Community loan funds pool small contributions from residents and lend them to local businesses at below-market rates. Decisions are made by committees of local volunteers, often with the borrower presenting in person. The funds are structured as nonprofit or cooperative vehicles, exempting them from some banking regulations while limiting the scale of individual loans.</p><ul><li>Average loan size: 35,000 dollars, repaid over three to five years.</li><li>Default rates below 2 percent — lower than comparable bank portfolios.</li><li>More than 60 percent of borrowers are first-generation business owners.</li></ul><p>The repayment figures have caught the attention of researchers. Local knowledge, it turns out, is an excellent predictor of creditworthiness — and social accountability is a powerful enforcement mechanism that no collection agency can replicate.</p><h2>Limits and critics</h2><p>Community funds are not a substitute for the banking system. They cannot finance a factory or smooth a liquidity crunch, and critics warn that shifting small-business credit to informal networks could leave gaps when neighborhoods face downturns together.</p><figure><img src="https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=1200&q=80" alt="Small shop interior with shelves"><figcaption>Local businesses are increasingly financed by the communities they serve.</figcaption></figure><p>Still, for thousands of small shops, the alternative was closing. The funds have quietly become an essential part of the economic plumbing — proof that the oldest form of credit, based on knowing your borrower, still works in the age of the algorithm.</p>',
 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=1600&q=80', 3, 'Priya Nair', 'published', 'Community Lending Rescues Small Shops as Banks Retreat', 'Community loan funds backed by local residents are filling the credit gap for small businesses — with default rates below 2 percent.',
 '2026-08-12T10:05:00.000Z'),

(7, 'Ancient Manuscript Archive Digitized and Opened to the Public', 'ancient-manuscript-archive-digitized-public',
 'A nine-year project has finished digitizing one of the world''s most significant manuscript collections, making 80,000 documents — some a thousand years old — freely available online.',
 '<p>After nine years of painstaking work, one of the world''s most significant manuscript collections has been fully digitized and opened to the public. The archive spans 80,000 documents — letters, ledgers, maps, medical texts and illuminated manuscripts — some of them more than a thousand years old.</p><p>The project was a collaboration between a national library, three universities and a team of 120 conservators and imaging specialists. Each document was photographed under calibrated lighting to reveal faded inks without damaging the originals.</p><blockquote>A manuscript locked in a vault belongs to no one. A manuscript on the open web belongs to everyone, forever.</blockquote><h2>Beyond scanning</h2><p>Digitization was only the first step. The archive''s search interface allows scholars to browse by century, region, language and handwriting style, and machine-transcription tools have already begun converting the most legible documents into searchable text.</p><ul><li>80,000 documents imaged at archival quality.</li><li>Text in 14 languages, fully catalogued and cross-referenced.</li><li>Free access for anyone, with open licensing for reuse.</li></ul><p>Early discoveries hint at the archive''s potential. Within weeks of the launch, researchers identified previously unknown correspondence between two medieval scholars, and a pharmacist''s ledger from 1648 that provides a rare record of early chemistry.</p><h2>What this means for scholarship</h2><p>Historians describe the launch as a turning point for fields that have traditionally depended on travel grants and institutional access. A doctoral student anywhere in the world can now study documents that once required a letter of introduction and a plane ticket.</p><figure><img src="https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=1200&q=80" alt="Rows of old books in a library"><figcaption>Documents once locked in climate-controlled vaults are now freely accessible online.</figcaption></figure><p>The library plans to add 40,000 more documents over the next five years, funded in part by the archive''s growing community of volunteers, who help transcribe and correct the machine-generated text.</p><p>For the conservators who spent a decade turning pages with gloved hands, the reward is simple: the archive will outlive every lock, fire and budget cut — because it no longer exists in only one place.</p>',
 'https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=1600&q=80', 4, 'Tomás Herrera', 'published', 'Ancient Manuscript Archive Opens to the Public Online', 'A nine-year digitization project has made 80,000 historic documents — some a thousand years old — freely available to anyone.',
 '2026-08-11T13:40:00.000Z'),

(8, 'New Telescope Survey Maps a Million Galaxies in Six Months', 'telescope-survey-million-galaxies-six-months',
 'A next-generation sky survey has catalogued one million galaxies in its first six months — a hundred times faster than its predecessor — and the dataset is already reshaping cosmology.',
 '<p>A next-generation sky survey has catalogued one million galaxies in its first six months of operation, a hundred times faster than the telescope it replaced and several years ahead of schedule. The early data release is already reshaping what astronomers know about how galaxies form and evolve.</p><p>The instrument achieves its speed through a wide field of view combined with an imaging sensor larger than any previously flown on a survey telescope. Each night it photographs a patch of sky the size of several hundred full moons, then repeats the process across a preplanned grid.</p><h2>Why a million galaxies matters</h2><p>Cosmology has a sample-size problem. Individual galaxies are shaped by accidents of history — collisions, mergers, bursts of star formation — and finding the underlying rules requires statistics. A million-galaxy catalogue turns patterns that were statistical noise into clear signals.</p><ul><li>First catalogued: 1,000,000+ galaxies in six months.</li><li>Survey depth reaches back 11 billion years.</li><li>Every galaxy imaged in six color bands, enabling distance estimates.</li></ul><blockquote>We are moving from studying individual objects to studying the population. That changes every question we can ask.</blockquote><h2>First results</h2><p>The early release has already produced surprises. The distribution of dwarf galaxies around large ones appears more uniform than models predict, and a previously unnoticed class of ultra-faint, extended galaxies has been identified — objects too diffuse to have been seen by any earlier survey.</p><figure><img src="https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?w=1200&q=80" alt="Satellite orbiting Earth"><figcaption>Wide-field survey instruments are transforming observational cosmology.</figcaption></figure><p>The full survey, scheduled to run for five years, is expected to catalogue more than twenty million galaxies and produce a movie of the changing sky — catching supernovae, asteroids and transient events as they happen.</p><p>For now, astronomers are doing what they always do with new instruments: discovering that the universe is stranger, richer and better organized than the last generation of data suggested.</p>',
 'https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?w=1600&q=80', 5, 'Amir Haddad', 'published', 'New Sky Survey Maps a Million Galaxies in Six Months', 'A next-generation telescope survey has catalogued a million galaxies at record speed, and its early data is already reshaping cosmology.',
 '2026-08-10T09:30:00.000Z'),

(9, 'City Transit Networks Embrace Off-Peak Pricing Experiment', 'city-transit-off-peak-pricing-experiment',
 'A dozen cities are testing lower fares during quiet hours to spread demand and revive ridership. Early results suggest the humble price signal can do what years of infrastructure spending could not.',
 '<p>A dozen cities across three continents have begun testing a simple idea with an old-fashioned mechanism: charge less for public transit when it is empty. The off-peak pricing experiments, running quietly for six months now, are producing results that transit planners describe as remarkable.</p><p>In the pilot cities, fares during mid-morning and early-afternoon hours have been cut by up to 40 percent, funded through small increases on peak-hour tickets. The goal was to shift flexible trips away from the rush-hour crush — and that is exactly what happened.</p><blockquote>We spent a decade and billions on capacity. It turns out a 30 percent discount does the work of a new tunnel for the price of a marketing campaign.</blockquote><h2>The numbers so far</h2><p>Ridership in off-peak windows rose by an average of 22 percent across the pilot cities, while peak-hour crowding fell by roughly 9 percent. Perhaps more significant: total ridership grew, not just shifted, suggesting the lower prices brought new passengers into the system.</p><ul><li>Off-peak ridership up 22 percent on average.</li><li>Peak crowding down 9 percent without added capacity.</li><li>Total fare revenue essentially flat, as volume offset the discount.</li></ul><h2>Why pricing works where building could not</h2><p>Transit demand is remarkably elastic when given the chance. The pilots showed that a large share of riders — students, part-time workers, caregivers, retirees — can choose when they travel, and will happily do so when rewarded. The peak, meanwhile, is dominated by commuters with fixed schedules, who keep paying full price.</p><figure><img src="https://images.unsplash.com/photo-1519501025264-65ba15a82390?w=1200&q=80" alt="City street at night with traffic"><figcaption>Cities are using fare structure, not concrete, to smooth demand.</figcaption></figure><p>Transit agencies are now designing permanent versions of the programs, with dynamic pricing tied to real-time crowding data. The infrastructure lesson is uncomfortable but clear: sometimes the smartest investment is the price tag.</p>',
 'https://images.unsplash.com/photo-1519501025264-65ba15a82390?w=1600&q=80', 1, 'Elena Petrova', 'published', 'Cities Try Off-Peak Pricing to Fix Transit Crowding', 'Lower fares during quiet hours are shifting ridership and reducing rush-hour crowding — without new infrastructure.',
 '2026-08-09T15:50:00.000Z'),

(10, 'Independent Bookstores Report Their Best Year in a Decade', 'independent-bookstores-best-year-decade',
 'Against all odds in the age of streaming, independent bookstores have posted their strongest sales in ten years. The reason, owners say, is not nostalgia — it is community.',
 '<p>Independent bookstores have just posted their best year in a decade, with sales up 18 percent and new stores opening at the fastest rate since records began. In an age of infinite streaming and infinite scrolling, the humble neighborhood bookshop has become an unlikely growth story.</p><p>The revival has been broad-based. Sales are up across fiction and nonfiction, in cities and small towns, among readers under 30 and over 60. The common thread, owners say, is not a rejection of technology but a hunger for curation and physical presence.</p><blockquote>An algorithm can sell you the book you already wanted. A bookseller introduces you to the book you did not know you needed. That is the whole business, and it cannot be automated.</blockquote><h2>What readers are buying</h2><p>The strongest categories have been translated fiction, nature writing and literary essay collections — genres that flourish on personal recommendation. Events have become the industry''s engine: readings, book clubs and author dinners now account for a fifth of many stores'' revenue.</p><ul><li>Sales up 18 percent year over year; 340 net new stores opened.</li><li>Translated fiction up 40 percent, driven by younger readers.</li><li>Store-hosted events now generate 20 percent of revenue at leading shops.</li></ul><h2>Why now</h2><p>Booksellers point to several forces converging. Screen fatigue is real and measurable. Publishers have rebalanced toward quality paperbacks with beautiful design. And the pandemic-era habit of supporting local businesses has hardened into a durable preference.</p><figure><img src="https://images.unsplash.com/photo-1526243741027-444d633d7365?w=1200&q=80" alt="Shelves of colorful books"><figcaption>Independent bookshops are opening at the fastest rate on record.</figcaption></figure><p>The question now is whether the boom can survive the next economic turn. Booksellers, for their part, are not planning for a boom at all — just for the steady, stubborn business of putting the right book in the right hands, one reader at a time.</p>',
 'https://images.unsplash.com/photo-1526243741027-444d633d7365?w=1600&q=80', 4, 'Nora El-Sayed', 'published', 'Independent Bookstores Post Best Year in a Decade', 'Sales at independent bookshops rose 18 percent as readers rediscover curation, community and the in-person book recommendation.',
 '2026-08-08T12:25:00.000Z'),

(11, 'Satellite Broadband Reaches Remote Coastal Villages', 'satellite-broadband-remote-coastal-villages',
 'Low-orbit satellite networks have connected 4,000 remote villages this year, bringing classrooms, clinics and fishing fleets online for the first time. The impact is being measured in ways engineers never expected.',
 '<p>The fishing village had never had a stable internet connection. Electricity arrived a generation ago; paved roads have not yet. This year, a low-orbit satellite terminal installed on the roof of the community hall changed the arithmetic of daily life.</p><p>It is one of 4,000 remote communities connected this year by the expanding constellations of low-earth-orbit satellites, part of a subsidized program targeting the hardest-to-reach settlements. Engineers measure success in uptime percentages; residents measure it in something else entirely.</p><h2>What a connection changes</h2><p>The first effect was economic. Fishermen now check weather forecasts before dawn and sell their catch through a regional auction app instead of accepting whatever the local buyer offered. The clinic holds video consultations with specialists in the provincial capital. Children attend remote lessons when monsoon flooding closes the road to the school.</p><blockquote>We did not know what we were missing because we had never had it. Now we cannot imagine the next storm season without it.</blockquote><ul><li>4,000 villages connected this year under the subsidy program.</li><li>Average installation time: under two hours, on any solid roof.</li><li>Local network operators trained in each community to maintain the service.</li></ul><h2>The economics of the last mile</h2><p>Satellite constellations have a structural advantage in remote areas: the marginal cost of serving one more village is nearly zero once the network is in orbit. The program bundles connectivity with solar power and locally managed Wi-Fi, addressing the reliability problems that killed earlier attempts.</p><figure><img src="https://images.unsplash.com/photo-1470770841072-f978cf4d019e?w=1200&q=80" alt="Lake and mountains at dusk"><figcaption>For remote settlements, satellite links are the first reliable connection in history.</figcaption></figure><p>The program''s managers are already planning the next phase: telemedicine partnerships, digital identity services and distance learning contracts. The infrastructure, they note, is now the easy part. The question is what to build on top of it — a question that, for the first time, the villages themselves can answer online.</p>',
 'https://images.unsplash.com/photo-1470770841072-f978cf4d019e?w=1600&q=80', 2, 'Kwame Mensah', 'published', 'Satellite Broadband Connects 4,000 Remote Villages', 'Low-orbit satellite networks brought reliable internet to thousands of remote coastal communities — transforming fishing, health care and education.',
 '2026-08-07T10:10:00.000Z'),

(12, 'How Local Food Hubs Are Reshaping Urban Markets', 'local-food-hubs-reshaping-urban-markets',
 'Consolidation centers that aggregate produce from nearby farms are cutting grocery costs and food waste at the same time. Cities are taking notice — and writing them into policy.',
 '<p>Every morning before dawn, vans from two dozen small farms arrive at a warehouse on the edge of the city. By eight, their produce has been sorted, packed and dispatched to 60 corner stores, restaurants and school kitchens. It is called a food hub — and it is quietly redrawing the map of how cities eat.</p><p>Food hubs solve a classic coordination problem. Small farms cannot supply a supermarket, and small buyers cannot absorb a farm''s whole harvest. The hub sits between them, aggregating supply and demand in both directions.</p><h2>The numbers behind the model</h2><p>Studies of the largest hubs show dramatic efficiency gains. Food travels less than half the distance of supermarket equivalents, spoilage falls because produce moves within 24 hours of harvest, and farmers keep a much larger share of the retail price.</p><ul><li>Average distance from farm to plate cut by 60 percent.</li><li>Food waste reduced by a third compared with conventional chains.</li><li>Farmers retain 70 to 80 percent of the retail price, versus 20 percent in traditional retail.</li></ul><blockquote>Efficiency in food has meant scale for scale''s sake. Hubs prove you can have efficiency and locality in the same supply chain.</blockquote><h2>From pilot to policy</h2><p>Cities have begun treating hubs as public infrastructure. Several municipalities now subsidize hub construction in underserved neighborhoods, and school procurement rules increasingly favor hub-sourced produce. The logic extends beyond food: the same model is being piloted for construction materials and repair services.</p><figure><img src="https://images.unsplash.com/photo-1488459716781-31db52582fe9?w=1200&q=80" alt="Fresh vegetables at a market stall"><figcaption>Hubs move produce from local farms to urban buyers within 24 hours of harvest.</figcaption></figure><p>For the farmers, the appeal is simple: a reliable buyer, a fair price and a harvest that no longer rots waiting for a truck. For the cities, it is fresher food, fewer emissions and an economy that keeps money circulating locally. The food hub, it turns out, is not just a warehouse — it is an argument.</p>',
 'https://images.unsplash.com/photo-1488459716781-31db52582fe9?w=1600&q=80', 3, 'Ravi Sharma', 'published', 'Local Food Hubs Cut Costs and Waste in Urban Supply Chains', 'Aggregation centers connecting small farms to urban buyers are reducing food miles by 60 percent and waste by a third.',
 '2026-08-06T14:00:00.000Z'),

(13, 'Inside the Quiet Boom of Repair Cafes', 'inside-quiet-boom-repair-cafes',
 'Volunteer-run workshops where neighbors fix broken electronics and furniture have tripled in number in five years. The movement is small, but it is changing how people think about ownership.',
 '<p>On the first Saturday of every month, the community center fills with tables, tools and the smell of solder. Residents bring broken toasters, torn jackets and laptops that will not boot. Volunteer fixers sit with them, teaching as they repair. Most items leave working. Nothing is charged.</p><p>Repair cafes have tripled in number over five years and now operate in more than 3,000 locations worldwide. The movement began as a protest against planned obsolescence; it has evolved into something more practical — a neighborhood institution.</p><h2>Why people come</h2><p>Surveys of visitors find three motivations in roughly equal measure: saving money, reducing waste and learning to fix things themselves. The social aspect, organizers say, is the secret ingredient that keeps the model alive.</p><ul><li>3,000+ repair cafes worldwide, triple the count of five years ago.</li><li>Typical success rate: 70 percent of items fixed on site.</li><li>More than half of first-time visitors return with another item.</li></ul><p>The environmental impact is modest in absolute terms but significant at the margin: each repair defers a purchase, and deferred purchases are where the embodied energy of manufacturing is saved.</p><h2>Policy catching up</h2><p>Governments have begun to notice. Right-to-repair laws now require manufacturers to provide spare parts and schematics, and several cities fund repair cafes as waste-reduction programs. Manufacturers, once hostile, are cautiously participating — some now staff repair events with their own technicians.</p><figure><img src="https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=1200&q=80" alt="Person working with tools at a workbench"><figcaption>Volunteer fixers teach neighbors to repair instead of replace.</figcaption></figure><p>The movement''s ambition remains deliberately small. Repair cafes are not trying to disrupt manufacturing — they are trying to remind people that a broken thing is not automatically a dead thing, and that the ability to fix belongs to everyone.</p>',
 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=1600&q=80', 4, 'Grace Kim', 'draft', '', '',
 NULL),

(14, 'The Return of the Night Train', 'the-return-of-the-night-train',
 'Sleeper services between European capitals are multiplying as travelers weigh carbon, cost and the simple pleasure of waking up somewhere new.',
 '<p>Sleeper trains are multiplying across the continent, revived by a generation of travelers weighing carbon emissions, hotel costs and the simple pleasure of waking up somewhere new. Two decades after budget airlines nearly killed them, night trains are back — and this time the economics look durable.</p><p>New routes now connect a dozen capital cities, with several more launching next year. The revival has been driven by a coalition of interests: climate-conscious travelers, governments seeking to meet emissions targets, and railway operators who discovered that a well-run sleeper can be profitable after all.</p><h2>Who rides the night train</h2><p>The passenger profile has shifted. Night trains were once the cheapest option for backpackers; today they attract professionals who value arriving at a city center before nine in the morning, and families who can afford a private cabin for less than the combined cost of flights and a hotel.</p><ul><li>New sleeper routes have more than doubled in five years.</li><li>Load factors above 80 percent on the most popular corridors.</li><li>Journeys under 1,000 km are now competitive door-to-door with flying.</li></ul><p>Operators are reinvesting: new rolling stock, digital booking and noise-insulated cabins. The experience gap with aviation, once decisive, has narrowed to a memory.</p><h2>The honest accounting</h2><p>Night trains are no climate panacea. Electrified routes emit a fraction of a flight; diesel stretches emit more. Infrastructure constraints mean sleeper capacity will grow slowly. Still, for the routes where they work, they offer the rare combination of lower emissions and a better experience — not a trade-off, but a bargain.</p><p>The night train''s advocates like to quote an old railway slogan: travel while you sleep. Two generations forgot how good that deal was. The current generation, it seems, is remembering.</p>',
 'https://images.unsplash.com/photo-1474487548417-781cb71495f3?w=1600&q=80', 1, 'Markus Weber', 'draft', '', '',
 NULL),

(15, 'Flash Analysis: Quarterly Market Report', 'flash-analysis-quarterly-market-report',
 'An early look at the quarterly figures and what they mean for the months ahead.',
 '<p>This analysis has been superseded by newer coverage. The quarterly figures have since been revised upward, and the outlook described here no longer reflects the current market environment.</p><p>The article is retained in the archive for reference.</p>',
 'https://images.unsplash.com/photo-1518186285589-2f7649de83e0?w=1600&q=80', 3, 'Desk', 'archived', '', '',
 NULL);

INSERT INTO featured_articles (article_id, position) VALUES
  ((SELECT id FROM articles WHERE slug = 'global-accord-ocean-conservation-120-nations'), 0),
  ((SELECT id FROM articles WHERE slug = 'open-source-ai-models-quietly-powering-enterprise'), 1),
  ((SELECT id FROM articles WHERE slug = 'long-form-journalism-making-a-comeback'), 2),
  ((SELECT id FROM articles WHERE slug = 'grid-scale-batteries-record-deployment'), 3);
